config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  resources :users do
    resources :twitter_streams
    resources :twitter_searches
    resources :twitter_graphs
    resources :twitter_id_searches
    resources :facebook_searches
  end
  
  post '/users/:user_id/twitter_streams/:id/stop' => 'twitter_streams#stop'
  post '/users/:user_id/twitter_searches/:id/stop' => 'twitter_searches#stop'
  post '/users/:user_id/twitter_graphs/:id/stop' => 'twitter_graphs#stop'
  post '/users/:user_id/facebook_searches/:id/stop' => 'facebook_searches#stop'
  
  get '/users/:user_id/twitter_streams/:id/tweets/poll' => 'twitter_streams#poll_tweets', :as => :poll_stream_tweets
  get '/users/:user_id/twitter_streams/:id/poll' => 'twitter_streams#poll_status', :as => :poll_stream_status
  
  get '/users/:user_id/twitter_searches/:id/tweets/poll' => 'twitter_searches#poll_tweets', :as => :poll_search_tweets
  get '/users/:user_id/twitter_searches/:id/poll' => 'twitter_searches#poll_status', :as => :poll_twitter_search_status
  
  get '/users/:user_id/twitter_graphs/:id/poll' => 'twitter_graphs#poll_status', :as => :poll_twitter_graph_status
  
  get '/users/:user_id/facebook_searches/:id/facebook_statuses/poll' => 'facebook_searches#poll_status_count', :as => :poll_facebook_statuses
  get '/users/:user_id/facebook_searches/:id/poll' => 'facebook_searches#poll_status', :as => :poll_fb_search_status
end

app/models/twitter_graph.rb
require 'open-uri'
class TwitterGraph < ActiveRecord::Base
  enum status: [:waiting, :running, :finished]
  after_initialize :set_default_status, :if => :new_record?
  belongs_to :user
  validates :query, presence: true
  before_destroy :delete_output

  def set_default_status
    self.status ||= :waiting
  end
  
  def self.is_terminated?(id)
    el = TwitterSearch.find(id)
    el == nil || el.status.to_s.eql?('finished')
  end
  
  def delete_output
    if self.output && File.exists?(self.output)
      FileUtils.rm(self.output)
    end
  end
  
  def terminated
    self.finished?
  end
  
  def get_graph
    self.update_attribute(:status, :running)
    Thread.new do
      begin
        tw_auth = TwitterAuth.where(:user_id => self.user_id).first
        access_token = prepare_access_token(tw_auth.consumer_key, tw_auth.consumer_secret, tw_auth.access_token, tw_auth.access_secret)
        main_user = get_user(self.query, access_token)
        edges = []
        if main_user
          sleep(5 * User.find(self.user_id).active_twitter_threads)
          nodes, edges = get_uid_data(main_user, edges, access_token, [])
          nodes.each do |node|
            n, edges = get_uid_data(node, edges, access_token, nodes + [main_user])
          end
          file = Rails.root.join("data", "twitter_graph_"+self.id.to_s+".csv")
          File.open(file, "w") do |f|
            edges.each do |edge|
              f.write(edge[0]["screen_name"]+","+edge[1]["screen_name"]+"\n")
            end
          end
          self.update_attribute(:output, file)
        else
          logger.warn "User not found: "+self.query
        end
        self.update_attribute(:status, :finished)
      rescue => e
        p e.message
        p e.backtrace.join("\n")
        self.update_attribute(:status, :finished)
      end
    end
  end
  
  def get_uid_data(node, edges, access_token, set)
    nodes = []
    friends = nil
    followers = nil
    # if set.size > 0
      # friends = get_mutual_friends_list(node["id"].to_s, set, access_token)
      # sleep(30 * User.find(self.user_id).twitter_graphs.where(:status => 1).size)
      # followers = get_mutual_followers_list(node["id"].to_s, set, access_token)
      # sleep(30 * User.find(self.user_id).twitter_graphs.where(:status => 1).size)
    # else
      friends = get_friends_list(node["id"].to_s, access_token)
      sleep(30 * User.find(self.user_id).twitter_graphs.where(:status => 1).size)
      followers = get_followers_list(node["id"].to_s, access_token)
      sleep(30 * User.find(self.user_id).twitter_graphs.where(:status => 1).size)
    # end
    if friends
      friends.each do |friend|
        nodes << friend unless nodes.include?(friend)
        edge = [node, friend]
        unless edges.include?(edge)
          edges << edge
        end
      end
    end
    if followers
      followers.each do |follower|
        nodes << follower unless nodes.include?(follower)
        edge = [follower, node]
        unless edges.include?(edge)
          edges << edge
        end
      end
    end
    return nodes, edges
  end
  
  def get_followers_list(uid, access_token)
    return nil if terminated
    key = get_key(uid)
    url = "https://api.twitter.com/1.1/followers/list.json?"+key+"="+uid+"&skip_status=true&include_user_entities=false&count=200"
    response = access_token.get(url)
    response = JSON.parse(response.body)
    if response.has_key?("errors")
      logger.error response["errors"]
      return nil
    end
    response["users"]
  end
  
  def get_friends_list(uid, access_token)
    return nil if terminated
    key = get_key(uid)
    url = "https://api.twitter.com/1.1/friends/list.json?"+key+"="+uid+"&skip_status=true&include_user_entities=false&count=200"
    response = access_token.get(url)
    response = JSON.parse(response.body)
    if response.has_key?("errors")
      logger.error response["errors"]
      return nil
    end
    response["users"]
  end
  
  def get_mutual_friends_list(uid, set, access_token)
    return nil if terminated
    friends = []
    key = get_key(uid).sub(/user_/,"")
    ids = set.map{|x| x["id"].to_s }.join(",")
    url = "https://api.twitter.com/1.1/friendships/show.json?source_"+key+"="+uid+"&target_id="+ids
    response = access_token.get(url)
    response = JSON.parse(response.body)
    return nil if response.has_key?("errors")
    response["relationships"].each do |rel|
      if rel["target"]["followed_by"].to_s.eql?("true")
        friends << rel["target"] unless friends.include?(rel["target"])
      end
    end
    friends
  end
  
  def get_mutual_followers_list(uid, set, access_token)
    return nil if terminated
    followers = []
    key = get_key(uid).sub(/user_/,"")
    ids = set.map{|x| x["id"].to_s }.join(",")
    url = "https://api.twitter.com/1.1/friendships/show.json?source_"+key+"="+uid+"&target_id="+ids
    response = access_token.get(url)
    response = JSON.parse(response.body)
    return nil if response.has_key?("errors")
    response["relationships"].each do |rel|
      if rel["target"]["following"].to_s.eql?("true")
        followers << rel["target"] unless followers.include?(rel["target"])
      end
    end
    followers
  end
  
  def get_user(uid, access_token)
    return nil if terminated
    key = get_key(uid)
    url = "https://api.twitter.com/1.1/users/show.json?"+key+"="+uid+"&include_entities=false"
    response = access_token.get(url)
    response = JSON.parse(response.body)
    if response.has_key?("errors")
      logger.error response["errors"]
      return nil
    end
    response
  end
  
  def get_key(uid)
    if uid =~ /^[0-9]+$/
      return "user_id"
    end
    return "screen_name"
  end
  
  def prepare_access_token(consumer_key, consumer_secret, oauth_token, oauth_token_secret)
    consumer = OAuth::Consumer.new(consumer_key, consumer_secret, { :site => "https://api.twitter.com", :scheme => :header })
    token_hash = { :oauth_token => oauth_token, :oauth_token_secret => oauth_token_secret }
    access_token = OAuth::AccessToken.from_hash(consumer, token_hash)
    return access_token
  end
end

app/controllers/twitter_graphs_controller.rb
class TwitterGraphsController < ApplicationController
  before_action :set_user
  before_action :check_tw_auth
  before_action :set_twitter_graph, only: [:show, :edit, :update, :destroy, :stop, :poll_status]

  # GET /twitter_graphs
  def index
    if @user && !@error
      @twitter_graphs = @user.twitter_graphs
      @page_title = 'twitter_graph'
      @sub_title = 'twitter graphs'
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_graphs/1
  def show
    if @twitter_graph
      @page_title = 'twitter_graph'
      @sub_title = 'twitter graph'
      respond_to do |format|
        format.html
        format.csv { render text: File.read(@twitter_graph.output) }
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_graphs/new
  def new
    if @user && !@error
      @twitter_graph = TwitterGraph.new
      @twitter_graph.user_id = @user.id
      @page_title = 'twitter_graph'
      @sub_title = 'New twitter graph'
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_graphs/1/edit
  def edit
  end

  # POST /twitter_graphs
  def create
    if @user && !@error
      @twitter_graph = TwitterGraph.new(twitter_graph_params)
      respond_to do |format|
        if @twitter_graph.save
          @user.twitter_graphs << @twitter_graph
          @twitter_graph.get_graph
          format.html { redirect_to user_twitter_graph_url(:id => @twitter_graph.id), notice: 'Twitter graph was successfully created.' }
        else
          format.html { render :new }
        end
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # PATCH/PUT /twitter_graphs/1
  def update
    respond_to do |format|
      if @twitter_graph.update(twitter_graph_params)
        format.html { redirect_to @twitter_graph, notice: 'Twitter graph was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /twitter_graphs/1
  def destroy
    @twitter_graph.destroy
    respond_to do |format|
      format.html { redirect_to user_twitter_graphs_url, notice: 'Twitter graph was successfully destroyed.' }
    end
  end
  
  def stop
    if @twitter_graph
      @twitter_graph.update_attribute(:status, :finished)
      respond_to do |format|
        format.json { render json: { 'message' => 'Graph stopped' }, status: 200 }
      end
    end
  end
  
  def poll_status
    if params[:element]
      @element = params[:element]
      respond_to do |format|
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_graph
      if @user && !@error
        @twitter_graph = TwitterGraph.where(:id => params[:id], :user_id => @user.id).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_graph_params
      params.require(:twitter_graph).permit(:query)
    end
end

app/views/twitter_graphs/_form.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<%= form_for(@twitter_graph, :url => user_twitter_graphs_path) do |f| %>
		<% if @twitter_graph.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@twitter_graph.errors.count, "error") %> prohibited this twitter_graph from being saved:</h2>

			<ul>
				<% @twitter_graph.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="form-group">
			<%= f.label :query %>
			<%= f.text_field :query, class: 'form-control' %>
		</div>

		<div class="actions">
			<%= f.submit "Create new Twitter Graph", :class => 'btn btn-info' %>
		</div>
		<% end %>
	</div>
</div>

app/views/twitter_graphs/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
    	<th>Query</th>
    	<th>Status</th>
    	<th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @twitter_graphs.each do |twitter_graph| %>
      <tr>
      	<td><%= twitter_graph.query %></td>
      	<% if twitter_graph.status.to_s.eql?('finished') %>
      	<td id="twg_<%= twitter_graph.id %>_status" class="pollable" data-url="<%= poll_twitter_graph_status_url(:user_id => current_user.id, :id => twitter_graph.id) %>"><%= twitter_graph.status %></td>
      	<% else %>
      	<td><%= twitter_graph.status %></td>
      	<% end %>
      	<td><%= twitter_graph.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', user_twitter_graph_path(:id => twitter_graph.id) %></td>
        <td><a href="#" class="stop-twitter-graph" data-id="<%= current_user.id %>" data-search-id="<%= twitter_graph.id %>">Stop</a></td>
        <td><%= link_to 'Destroy', user_twitter_graph_path(:id => twitter_graph.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/twitter_graphs/edit.html.erb
<h1>Editing Twitter Graph</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_graph %> |
<%= link_to 'Back', user_twitter_graphs_path %>

app/views/twitter_graphs/index.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>This interface allows you to recreate the social network of a Twitter user account.</p>
		<p>If you have any stored Twitter Graphs they will be listed here.</p>
		<p><b>NB:</b> You are allowed to run only 2 Twitter Stream, Search or Graph queries at a time. If you do not see the 'New' button, wait for one of your other queries to finish.</p>
	</div>
</div>
<% if current_user.twitter_graphs.size > 0 %>
<div id="twitter-graph-list">
	<%= render 'twitter_graphs/list' %>
</div>
<br>
<% end %>
<% if current_user.has_open_twitter_slots? %>
<%= link_to 'New Twitter Graph', new_user_twitter_graph_path, :class => 'btn btn-info' %><br><br>
<% else %>
<p>Please wait until your previous Twitter searches, streams or graphs have finished before adding a new one.</p>
<% end %>
<%= link_to 'Back', :root, :class => 'btn btn-default' %>

app/views/twitter_graphs/new.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>Enter a Twitter user id or name tag to recreate that user's social network.</p>
	</div>
</div>
<%= render 'form' %>

<%= link_to 'Back', user_twitter_graphs_path, :class => 'btn btn-default' %>

app/views/twitter_graphs/poll_status.js.erb
<% if @element %>
$('td#<%= @element %>').html("<%= @twitter_graph.status.to_s %>");
<% if !@twitter_graph.status.to_s.eql?('finished') %>
if (document.getElementById("<%= @element %>")) {
	poll($('#<%= @element %>').data('url'), $('#<%= @element %>').attr('id'));
}
<% end %>
<% end %>

app/views/twitter_graphs/show.html.erb
<%= link_to 'Back to Twitter Graphs', user_twitter_graphs_path, :class => 'btn btn-default' %>
<br>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<h3>Query details</h3>
		<table>
			<tr>
				<th>Query</th>
				<td><%= @twitter_graph.query %></td>
			</tr>
      		<% if !@twitter_graph.status.to_s.eql?('finished') %>
      		<tr>
      			<th>Status</th>
      			<td id="tw_graph_<%= @twitter_graph.id %>_status" class="pollable" data-url="<%= poll_twitter_graph_status_url(:user_id => current_user.id, :id => @twitter_graph.id) %>"><%= @twitter_graph.status %></td>
      		</tr>
      		<tr>
      			<th></th>
      			<td><a href="#" class="stop-twitter-graph btn-xs btn-warning" data-id="<%= current_user.id %>" data-graph-id="<%= @twitter_graph.id %>">Stop</a></td>
      		</tr>
      		<% else %>
      		<tr>
      			<th>Status</th>
      			<td><%= @twitter_graph.status %></td>
      		</tr>
      		<% end %>
      		<% if @twitter_graph.output && File.exists?(@twitter_graph.output) %>
      		<tr>
      			<th></th>
      			<td><a href="/users/<%= @user.id %>/twitter_graphs/<%= @twitter_graph.id %>.csv" target="_blank" class="btn btn-xs btn-info">Download graph</a></td>
      		</tr>
      		<% end %>
		</table>
	</div>
</div>
<br>