config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  resources :users do
    resources :twitter_streams
    resources :twitter_searches
    resources :twitter_graphs
    resources :twitter_id_searches
    resources :facebook_searches
  end
  
  post '/users/:user_id/twitter_streams/:id/stop' => 'twitter_streams#stop'
  post '/users/:user_id/twitter_searches/:id/stop' => 'twitter_searches#stop'
  post '/users/:user_id/twitter_graphs/:id/stop' => 'twitter_graphs#stop'
  post '/users/:user_id/facebook_searches/:id/stop' => 'facebook_searches#stop'
  
  get '/users/:user_id/twitter_streams/:id/tweets/poll' => 'twitter_streams#poll_tweets', :as => :poll_stream_tweets
  get '/users/:user_id/twitter_streams/:id/poll' => 'twitter_streams#poll_status', :as => :poll_stream_status
  
  get '/users/:user_id/twitter_searches/:id/tweets/poll' => 'twitter_searches#poll_tweets', :as => :poll_search_tweets
  get '/users/:user_id/twitter_searches/:id/poll' => 'twitter_searches#poll_status', :as => :poll_twitter_search_status
  
  get '/users/:user_id/twitter_graphs/:id/poll' => 'twitter_graphs#poll_status', :as => :poll_twitter_graph_status
  
  get '/users/:user_id/facebook_searches/:id/facebook_statuses/poll' => 'facebook_searches#poll_status_count', :as => :poll_facebook_statuses
  get '/users/:user_id/facebook_searches/:id/poll' => 'facebook_searches#poll_status', :as => :poll_fb_search_status
end

app/models/facebook_search.rb
require 'open-uri'
class FacebookSearch < ActiveRecord::Base
  enum status: [:waiting, :running, :finished]
  after_initialize :set_default_status, :if => :new_record?
  belongs_to :user
  has_and_belongs_to_many :facebook_statuses
  validates :query, presence: true

  def set_default_status
    self.status ||= :waiting
  end
  
  def self.is_terminated?(id)
    el = FacebookSearch.find(id)
    el == nil || el.status.to_s.eql?('finished')
  end
  
  def get_statuses(facebook)
    self.update_attribute(:status, :running)
    Thread.new do
      page_collection = facebook.search(self.query, {:type => "page", :limit => 1000})
      terminated = false
      if page_collection.size > 0
        begin
          page_collection.each do |page|
            terminated = FacebookSearch.is_terminated?(self.id)
            unless terminated
              posts_collection = facebook.get_connections(page["id"], "posts", limit: 100, filter: 'stream')
              if posts_collection.size > 0
                begin
                  posts_collection.each do |post|
                    terminated = FacebookSearch.is_terminated?(self.id)
                    unless terminated
                      facebook_status = FacebookStatus.from_idstr_and_uid(post["id"],page["id"],facebook,nil,false)
                      if facebook_status != nil && !self.facebook_statuses.include?(facebook_status)
                        self.facebook_statuses << facebook_status
                        # Get comments to status
                        comment_count = facebook.get_object(post["id"], {:fields => "comments.summary(true)"})['comments']['summary']['total_count']
                        if comment_count > 0
                          comments = facebook.get_connections(post["id"], "comments", limit: 100, filter: 'stream')
                          begin
                            comments.each do |comment|
                              terminated = FacebookSearch.is_terminated?(self.id)
                              unless terminated
                                comment_status = FacebookStatus.from_idstr_and_uid(comment["id"],comment["from"]["id"],facebook,post["id"],true)
                                if comment_status != nil && !self.facebook_statuses.include?(comment_status)
                                  self.facebook_statuses << comment_status
                                end
                              end
                            end
                            comments = comments.next_page
                          end while comments != nil && !terminated
                        end
                      end
                    end
                  end
                  posts_collection = posts_collection.next_page
                end while posts_collection != nil && !terminated
              end
            end
          end
          page_collection = page_collection.next_page
        end while page_collection != nil && !terminated
      end
      self.update_attribute(:status, :finished)
    end
  end
end

app/controllers/facebook_searches_controller.rb
class FacebookSearchesController < ApplicationController
  before_action :set_user
  before_action :set_facebook_search, only: [:show, :edit, :update, :destroy, :stop, :poll_status_count, :poll_status]

  # GET /facebook_searches
  # GET /facebook_searches.json
  def index
    if @user && !@error
      @facebook_searches = @user.facebook_searches
      @page_title = 'facebook_search'
      @sub_title = 'facebook searches'
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /facebook_searches/1
  # GET /facebook_searches/1.json
  def show
    @page_title = 'facebook_search'
    @sub_title = 'facebook search'
    if @facebook_search
      page = params[:page] || 1
      number = params[:number] || 10
      @facebook_statuses = @facebook_search.facebook_statuses.paginate(:page => page, :per_page => number)
      respond_to do |format|
        format.html
        format.csv { render text: @facebook_search.facebook_statuses.to_csv(col_sep: "\t") }
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /facebook_searches/new
  def new
    @page_title = 'facebook_search'
    @sub_title = 'new facebook search'
    if @user && !@error
      @facebook_search = FacebookSearch.new
      @facebook_search.user_id = @user.id
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /facebook_searches/1/edit
  def edit
  end

  # POST /facebook_searches
  # POST /facebook_searches.json
  def create
    if @user && !@error
      @facebook_search = FacebookSearch.new(facebook_search_params)
      respond_to do |format|
        if @facebook_search.save
          @user.facebook_searches << @facebook_search
          @facebook_search.get_statuses(@user.facebook)
          format.html { redirect_to user_facebook_search_url(:id => @facebook_search.id), notice: 'Facebook search was successfully created.' }
          format.json { render :show, status: :created, location: @facebook_search }
        else
          format.html { render :new }
          format.json { render json: @facebook_search.errors, status: :unprocessable_entity }
        end
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # PATCH/PUT /facebook_searches/1
  # PATCH/PUT /facebook_searches/1.json
  def update
    respond_to do |format|
      if @facebook_search.update(facebook_search_params)
        format.html { redirect_to @facebook_search, notice: 'Facebook search was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebook_search }
      else
        format.html { render :edit }
        format.json { render json: @facebook_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebook_searches/1
  # DELETE /facebook_searches/1.json
  def destroy
    @facebook_search.destroy
    respond_to do |format|
      format.html { redirect_to user_facebook_searches_url, notice: 'Facebook search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def stop
    if @facebook_search
      @facebook_search.update_attribute(:status, :finished)
      respond_to do |format|
        format.json { render json: { 'message' => 'Search stopped' }, status: 200 }
      end
    end
  end
  
  def poll_status_count
    if params[:element]
      @element = params[:element]
      respond_to do |format|
        format.js
      end
    end
  end
  
  def poll_status
    if params[:element]
      @element = params[:element]
      respond_to do |format|
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebook_search
      if @user && !@error
        @facebook_search = FacebookSearch.where(:id => params[:id], :user_id => @user.id).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebook_search_params
      params.require(:facebook_search).permit(:query)
      # params.fetch(:facebook_search, {})
    end
end

app/helpers/facebook_searches_helper.rb
module FacebookSearchesHelper
end

app/views/facebook_searches/_form.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<%= form_for(@facebook_search, :url => user_facebook_searches_path) do |f| %>
		<% if @facebook_search.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@facebook_search.errors.count, "error") %> prohibited this facebook_search from being saved:</h2>

			<ul>
				<% @facebook_search.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="form-group">
			<%= f.label :query %>
			<%= f.text_field :query, class: 'form-control' %>
		</div>

		<div class="actions">
			<%= f.submit 'Create new Facebook Search', :class => 'btn btn-info' %>
		</div>
		<% end %>
	</div>
</div>

app/views/facebook_searches/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
    	<th>Query</th>
    	<th>Facebook status count</th>
    	<th>Status</th>
    	<th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facebook_searches.each do |facebook_search| %>
      <tr>
      	<td><%= facebook_search.query %></td>
      	<% if !facebook_search.status.to_s.eql?('finished') %>
      	<td id="fb_<%= facebook_search.id %>_count" class="pollable" data-url="<%= poll_facebook_statuses_url(:user_id => current_user.id, :id => facebook_search.id) %>"><%= facebook_search.facebook_statuses.size %></td>
      	<td id="fb_<%= facebook_search.id %>_status" class="pollable" data-url="<%= poll_fb_search_status_url(:user_id => current_user.id, :id => facebook_search.id) %>"><%= facebook_search.status %></td>
      	<% else %>
      	<td><%= facebook_search.facebook_statuses.size %></td>
      	<td><%= facebook_search.status %></td>
      	<% end %>
      	<td><%= facebook_search.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', user_facebook_search_path(:id => facebook_search.id) %></td>
        <td><a href="#" class="stop-facebook-search" data-id="<%= current_user.id %>" data-search-id="<%= facebook_search.id %>">Stop</a></td>
        <td><%= link_to 'Destroy', user_facebook_search_path(:id => facebook_search.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/facebook_searches/edit.html.erb
<h1>Editing Facebook Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @facebook_search %> |
<%= link_to 'Back', user_facebook_searches_path %>

app/views/facebook_searches/index.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>This interface allows you to search for Facebook status updates and comments. All retrievable updates and comments posted on pages whose names match your query will be stored.</p>
		<p>If you have any stored Facebook Searches they will be listed here.</p>
		<p><b>NB:</b> You are allowed to run only 1 Facebook Search at a time.</p>
	</div>
</div>
<% if current_user.facebook_searches.size > 0 %>
<div id="facebook-search-list">
	<%= render 'facebook_searches/list' %>
</div>
<br>
<% end %>
<% if current_user.has_open_facebook_slots? %>
<%= link_to 'New Facebook search', new_user_facebook_search_path, :class => 'btn btn-info' %><br><br>
<% else %>
<p>Please wait until your previous search is finished before adding a new one.</p>
<% end %>
<%= link_to 'Back', :root, :class => 'btn btn-default' %>

app/views/facebook_searches/new.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>Enter a query to search for Facebook status updates and comments.</p>
		<p>
			The searcher will first retrieve all <b>pages</b> whose name or description matches your query.
			Next, all retrievable <b>status updates</b> of those pages are retrieved, followed by all <b>comments</b> to those statuses.
		</p>
		<p>Keep in mind that your query most likely will NOT occur in the literal text of the updates and comments. However, if you choose your query carefully, you can assume that the overall subject of the updates and comments does match your query.</p>
		<p>Example queries:
			<ul>
				<li><label>Token search:</label> Obama</li>
				<li><label>Term search:</label> "Barack Obama"</li>
				<li><label>Boolean AND:</label> potus "Barack Obama"</li>
				<li><label>Boolean OR:</label> "White House" | "Barack Obama" (note the spaces)</li>
			</ul>
		</p>
	</div>
</div>
<%= render 'form' %>

<%= link_to 'Back', user_facebook_searches_path, :class => 'btn btn-default' %>

app/views/facebook_searches/poll_status.js.erb
<% if @element %>
$('td#<%= @element %>').html("<%= @facebook_search.status.to_s %>");
<% if !@facebook_search.status.to_s.eql?('finished') %>
if (document.getElementById("<%= @element %>")) {
	poll($('#<%= @element %>').data('url'), $('#<%= @element %>').attr('id'));
}
<% end %>
<% end %>

app/views/facebook_searches/poll_status_count.js.erb
<% if @element %>
$('td#<%= @element %>').html("<%= @facebook_search.facebook_statuses.size.to_s %>");
<% if !@facebook_search.status.to_s.eql?('finished') %>
if (document.getElementById("<%= @element %>")) {
	poll($('#<%= @element %>').data('url'), $('#<%= @element %>').attr('id'));
}
<% end %>
<% end %>

app/views/facebook_searches/show.html.erb
<%= link_to 'Back to Facebook Searches', user_facebook_searches_path, :class => 'btn btn-default' %>
<br>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<h3>Query details</h3>
		<table>
			<tr>
				<th>Query</th>
				<td><%= @facebook_search.query %></td>
			</tr>
      		<% if !@facebook_search.status.to_s.eql?('finished') %>
      		<tr>
      			<th>Status</th>
      			<td id="fb_search_<%= @facebook_search.id %>_status" class="pollable" data-url="<%= poll_fb_search_status_url(:user_id => current_user.id, :id => @facebook_search.id) %>"><%= @facebook_search.status %></td>
      		</tr>
      		<tr>
      			<th>Result count</th>
      			<td id="fb_search_<%= @facebook_search.id %>_status_count" class="pollable" data-url="<%= poll_facebook_statuses_url(:user_id => current_user.id, :id => @facebook_search.id) %>"><%= @facebook_search.facebook_statuses.size %></td>
      		</tr>
      		<tr>
      			<th></th>
      			<td><a href="#" class="stop-facebook-search btn-xs btn-warning" data-id="<%= current_user.id %>" data-search-id="<%= @facebook_search.id %>">Stop</a></td>
      		</tr>
      		<% else %>
      		<tr>
      			<th>Status</th>
      			<td><%= @facebook_search.status %></td>
      		</tr>
      		<tr>
      			<th>Result count</th>
      			<td><%= @facebook_search.facebook_statuses.size %></td>
      		</tr>
      		<% end %>
      		<% if @facebook_search.facebook_statuses.size > 0 %>
      		<tr>
      			<th></th>
      			<td><a href="/users/<%= @user.id %>/facebook_searches/<%= @facebook_search.id %>.csv" target="_blank" class="btn btn-xs btn-info">Download Facebook statuses</a></td>
      		</tr>
      		<% end %>
		</table>
	</div>
</div>
<br>
<div class="row">
	<div id="facebook-statuses" class="col-xs-12">
		<span class="h3">
			<div class="info-group info-group-right">
				<div class="info">Refresh the page to show new results.</div>
				<div class="content">Query results</div>
			</div>
		</span>
		<%= render 'facebook_statuses/index' %>
	</div>
</div>
<br>