config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  resources :users do
    resources :twitter_streams
    resources :twitter_searches
    resources :twitter_graphs
    resources :twitter_id_searches
    resources :facebook_searches
  end
  
  post '/users/:user_id/twitter_streams/:id/stop' => 'twitter_streams#stop'
  post '/users/:user_id/twitter_searches/:id/stop' => 'twitter_searches#stop'
  post '/users/:user_id/twitter_graphs/:id/stop' => 'twitter_graphs#stop'
  post '/users/:user_id/facebook_searches/:id/stop' => 'facebook_searches#stop'
  
  get '/users/:user_id/twitter_streams/:id/tweets/poll' => 'twitter_streams#poll_tweets', :as => :poll_stream_tweets
  get '/users/:user_id/twitter_streams/:id/poll' => 'twitter_streams#poll_status', :as => :poll_stream_status
  
  get '/users/:user_id/twitter_searches/:id/tweets/poll' => 'twitter_searches#poll_tweets', :as => :poll_search_tweets
  get '/users/:user_id/twitter_searches/:id/poll' => 'twitter_searches#poll_status', :as => :poll_twitter_search_status
  
  get '/users/:user_id/twitter_graphs/:id/poll' => 'twitter_graphs#poll_status', :as => :poll_twitter_graph_status
  
  get '/users/:user_id/facebook_searches/:id/facebook_statuses/poll' => 'facebook_searches#poll_status_count', :as => :poll_facebook_statuses
  get '/users/:user_id/facebook_searches/:id/poll' => 'facebook_searches#poll_status', :as => :poll_fb_search_status
end

app/models/twitter_search.rb
require 'open-uri'
class TwitterSearch < ActiveRecord::Base
  enum status: [:waiting, :running, :finished]
  after_initialize :set_default_status, :if => :new_record?
  belongs_to :user
  has_and_belongs_to_many :tweets
  validates :query, presence: true

  def set_default_status
    self.status ||= :waiting
  end
  
  def self.is_terminated?(id)
    el = TwitterSearch.find(id)
    el == nil || el.status.to_s.eql?('finished')
  end
  
  def get_tweets
    self.update_attribute(:status, :running)
    Thread.new do
      terminated = false
      tw_auth = TwitterAuth.where(:user_id => self.user_id).first
      access_token = prepare_access_token(tw_auth.consumer_key, tw_auth.consumer_secret, tw_auth.access_token, tw_auth.access_secret)
      (0..9).to_a.reverse.each do |i|
        day_total = 0
        date = (Time.now - i.days).strftime("%Y-%m-%d")
        next_date = i == 0 ? nil : (Time.now - (i - 1).days).strftime("%Y-%m-%d")
        url = "https://api.twitter.com/1.1/search/tweets.json?count=100&q="+URI::encode(self.query)+"&result_type=mixed&since="+date.to_s
        if next_date != nil
          url = url + '&until='+next_date.to_s
        end
        begin
          terminated = TwitterSearch.is_terminated?(self.id)
          response = nil
          unless terminated
            response = access_token.get(url)
            response = JSON.parse(response.body)
            if response.has_key?("errors")
              p "*** ERROR "+response["errors"][0]["code"].to_s+": "+response["errors"][0]["message"]
              if response["errors"][0]["code"] == 88
                p "*** SLEEPING..."
                sleep(900)
                response = access_token.get(url)
                response = JSON.parse(response.body)
              else
                response = nil
                url = nil
              end
            end
          end
          if response != nil && !terminated
            response["statuses"].each do |status|
              terminated = TwitterSearch.is_terminated?(self.id)
              tweet = Tweet.from_json(status)
              if !tweet.blank? && !self.tweets.include?(tweet) && !terminated
                day_total = day_total + 1
                self.tweets << tweet
                if day_total == 1000
                  break
                end
              end
            end
            if day_total >= 1000 || terminated || !response["search_metadata"].has_key?("next_results") || response["search_metadata"]["next_results"].blank?
              url = nil
            else
              url = "https://api.twitter.com/1.1/search/tweets.json"+response["search_metadata"]["next_results"]
            end
            sleep(5 * User.find(self.user_id).active_twitter_threads)
          end
          if i == 0
            self.update_attribute(:status, :finished)
          end
        rescue => e
          p e.message
          p e.backtrace.join("\n")
        end while url != nil && !terminated
      end
      # self.update_attribute(:status, :finished)
    end
  end
  
  def prepare_access_token(consumer_key, consumer_secret, oauth_token, oauth_token_secret)
    consumer = OAuth::Consumer.new(consumer_key, consumer_secret, { :site => "https://api.twitter.com", :scheme => :header })
    token_hash = { :oauth_token => oauth_token, :oauth_token_secret => oauth_token_secret }
    access_token = OAuth::AccessToken.from_hash(consumer, token_hash)
    return access_token
  end
end

app/controllers/twitter_searches_controller.rb
require 'csv'
class TwitterSearchesController < ApplicationController
  before_action :set_user
  before_action :check_tw_auth
  before_action :set_twitter_search, only: [:show, :edit, :update, :destroy, :stop, :poll_tweets, :poll_status]

  # GET /twitter_searches
  # GET /twitter_searches.json
  def index
    if @user && !@error
      @twitter_searches = @user.twitter_searches
      @page_title = 'twitter_search'
      @sub_title = 'twitter searches'
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_searches/1
  # GET /twitter_searches/1.json
  def show
    if @twitter_search
      page = params[:page] || 1
      number = params[:number] || 10
      @tweets = @twitter_search.tweets.paginate(:page => page, :per_page => number)
      @page_title = 'twitter_search'
      @sub_title = 'twitter search'
      respond_to do |format|
        format.html
        format.csv { render text: @twitter_search.tweets.to_csv(col_sep: "\t") }
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_searches/new
  def new
    if @user && !@error
      @twitter_search = TwitterSearch.new
      @twitter_search.user_id = @user.id
      @page_title = 'twitter_search'
      @sub_title = 'New twitter search'
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # GET /twitter_searches/1/edit
  def edit
  end

  # POST /twitter_searches
  # POST /twitter_searches.json
  def create
    if @user && !@error
      @twitter_search = TwitterSearch.new(twitter_search_params)
      respond_to do |format|
        if @twitter_search.save
          @user.twitter_searches << @twitter_search
          @twitter_search.get_tweets
          format.html { redirect_to user_twitter_search_url(:id => @twitter_search.id), notice: 'Twitter search was successfully created.' }
          format.json { render :show, status: :created, location: @twitter_search }
        else
          format.html { render :new }
          format.json { render json: @twitter_search.errors, status: :unprocessable_entity }
        end
      end
    else
      if !@error
        @error = 'No user'
      end
      redirect_to :root, alert: @error
    end
  end

  # PATCH/PUT /twitter_searches/1
  # PATCH/PUT /twitter_searches/1.json
  def update
    respond_to do |format|
      if @twitter_search.update(twitter_search_params)
        format.html { redirect_to @twitter_search, notice: 'Twitter search was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_search }
      else
        format.html { render :edit }
        format.json { render json: @twitter_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_searches/1
  # DELETE /twitter_searches/1.json
  def destroy
    @twitter_search.destroy
    respond_to do |format|
      format.html { redirect_to user_twitter_searches_url, notice: 'Twitter search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def stop
    if @twitter_search
      @twitter_search.update_attribute(:status, :finished)
      respond_to do |format|
        format.json { render json: { 'message' => 'Search stopped' }, status: 200 }
      end
    end
  end
  
  def poll_tweets
    if params[:element]
      @element = params[:element]
      respond_to do |format|
        format.js
      end
    end
  end
  
  def poll_status
    if params[:element]
      @element = params[:element]
      respond_to do |format|
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_search
      if @user && !@error
        @twitter_search = TwitterSearch.where(:id => params[:id], :user_id => @user.id).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_search_params
      params.require(:twitter_search).permit(:query)
      # params.fetch(:twitter_search, {})
    end
end

app/helpers/twitter_searches_helper.rb
module TwitterSearchesHelper
end

app/views/twitter_searches/_form.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<%= form_for(@twitter_search, :url => user_twitter_searches_path) do |f| %>
		<% if @twitter_search.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@twitter_search.errors.count, "error") %> prohibited this twitter_search from being saved:</h2>

			<ul>
				<% @twitter_search.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="form-group">
			<%= f.label :query %>
			<%= f.text_field :query, class: 'form-control' %>
		</div>

		<div class="actions">
			<%= f.submit "Create new Twitter Search", :class => 'btn btn-info' %>
		</div>
		<% end %>
	</div>
</div>

app/views/twitter_searches/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
    	<th>Query</th>
    	<th>Tweet count</th>
    	<th>Status</th>
    	<th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @twitter_searches.each do |twitter_search| %>
      <tr>
      	<td><%= twitter_search.query %></td>
      	<% if !twitter_search.status.to_s.eql?('finished') %>
      	<td id="tws_<%= twitter_search.id %>_count" class="pollable" data-url="<%= poll_search_tweets_url(:user_id => current_user.id, :id => twitter_search.id) %>"><%= twitter_search.tweets.size %></td>
      	<td id="tws_<%= twitter_search.id %>_status" class="pollable" data-url="<%= poll_twitter_search_status_url(:user_id => current_user.id, :id => twitter_search.id) %>"><%= twitter_search.status %></td>
      	<% else %>
      	<td><%= twitter_search.tweets.size %></td>
      	<td><%= twitter_search.status %></td>
      	<% end %>
      	<td><%= twitter_search.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', user_twitter_search_path(:id => twitter_search.id) %></td>
        <td><a href="#" class="stop-twitter-search" data-id="<%= current_user.id %>" data-search-id="<%= twitter_search.id %>">Stop</a></td>
        <td><%= link_to 'Destroy', user_twitter_search_path(:id => twitter_search.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/twitter_searches/edit.html.erb
<h1>Editing Twitter Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_search %> |
<%= link_to 'Back', user_twitter_searches_path %>

app/views/twitter_searches/index.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>This interface allows you to search for tweets in the past. Twitter allows search and retrieval of tweets up to 1 week ago.</p>
		<p>If you have any stored Twitter Searches they will be listed here.</p>
		<p><b>NB:</b> You are allowed to run only 2 Twitter Stream or Search queries at a time. If you do not see the 'New' button, wait for one of your other queries to finish.</p>
	</div>
</div>
<% if current_user.twitter_searches.size > 0 %>
<div id="twitter-search-list">
	<%= render 'twitter_searches/list' %>
</div>
<br>
<% end %>
<% if current_user.has_open_twitter_slots? %>
<%= link_to 'New Twitter Search', new_user_twitter_search_path, :class => 'btn btn-info' %><br><br>
<% else %>
<p>Please wait until your previous Twitter searches or streams have finished before adding a new one.</p>
<% end %>
<%= link_to 'Back', :root, :class => 'btn btn-default' %>

app/views/twitter_searches/new.html.erb
<div class="panel panel-info">
	<div class="panel-body">
		<p>Enter a query to search for tweets up to 1 week ago.</p>
		<p>Example queries:
			<ul>
				<li><label>Token search:</label> Obama</li>
				<li><label>Term search:</label> "Barack Obama"</li>
				<li><label>Hashtag search:</label> #potus</li>
				<li><label>Term search:</label> "Barack Obama"</li>
				<li><label>Boolean AND:</label> #potus "Barack Obama"</li>
				<li><label>Boolean OR:</label> "White House" OR "Barack Obama"</li>
				<li><label>Exclusion:</label> Obama -Barack</li>
			</ul>
		</p>
		<p>See also <a href="https://dev.twitter.com/rest/public/search" target="_blank">this page</a>.</p>
	</div>
</div>
<%= render 'form' %>

<%= link_to 'Back', user_twitter_searches_path, :class => 'btn btn-default' %>

app/views/twitter_searches/poll_status.js.erb
<% if @element %>
$('td#<%= @element %>').html("<%= @twitter_search.status.to_s %>");
<% if !@twitter_search.status.to_s.eql?('finished') %>
if (document.getElementById("<%= @element %>")) {
	poll($('#<%= @element %>').data('url'), $('#<%= @element %>').attr('id'));
}
<% end %>
<% end %>

app/views/twitter_searches/poll_tweets.js.erb
<% if @element %>
$('td#<%= @element %>').html("<%= @twitter_search.tweets.size.to_s %>");
<% if !@twitter_search.status.to_s.eql?('finished') %>
if (document.getElementById("<%= @element %>")) {
	poll($('#<%= @element %>').data('url'), $('#<%= @element %>').attr('id'));
}
<% end %>
<% end %>

app/views/twitter_searches/show.html.erb
<%= link_to 'Back to Twitter Searches', user_twitter_searches_path, :class => 'btn btn-default' %>
<br>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<h3>Query details</h3>
		<table>
			<tr>
				<th>Query</th>
				<td><%= @twitter_search.query %></td>
			</tr>
      		<% if !@twitter_search.status.to_s.eql?('finished') %>
      		<tr>
      			<th>Status</th>
      			<td id="tw_search_<%= @twitter_search.id %>_status" class="pollable" data-url="<%= poll_twitter_search_status_url(:user_id => current_user.id, :id => @twitter_search.id) %>"><%= @twitter_search.status %></td>
      		</tr>
      		<tr>
      			<th>Result count</th>
      			<td id="tw_search_<%= @twitter_search.id %>_status_count" class="pollable" data-url="<%= poll_search_tweets_url(:user_id => current_user.id, :id => @twitter_search.id) %>"><%= @twitter_search.tweets.size %></td>
      		</tr>
      		<tr>
      			<th></th>
      			<td><a href="#" class="stop-twitter-search btn-xs btn-warning" data-id="<%= current_user.id %>" data-search-id="<%= @twitter_search.id %>">Stop</a></td>
      		</tr>
      		<% else %>
      		<tr>
      			<th>Status</th>
      			<td><%= @twitter_search.status %></td>
      		</tr>
      		<tr>
      			<th>Result count</th>
      			<td><%= @twitter_search.tweets.size %></td>
      		</tr>
      		<% end %>
      		<% if @twitter_search.tweets.size > 0 %>
      		<tr>
      			<th></th>
      			<td><a href="/users/<%= @user.id %>/twitter_searches/<%= @twitter_search.id %>.csv" target="_blank" class="btn btn-xs btn-info">Download tweets</a></td>
      		</tr>
      		<% end %>
		</table>
	</div>
</div>
<br>
<div class="row">
	<div id="tweets" class="col-xs-12">
		<span class="h3">
			<div class="info-group info-group-right">
				<div class="info">Refresh the page to show new results.</div>
				<div class="content">Query results</div>
			</div>
		</span>
		<%= render 'tweets/index' %>
	</div>
</div>
<br>