config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  resources :users do
    resources :twitter_streams
    resources :twitter_searches
    resources :twitter_graphs
    resources :twitter_id_searches
    resources :facebook_searches
  end
  
  post '/users/:user_id/twitter_streams/:id/stop' => 'twitter_streams#stop'
  post '/users/:user_id/twitter_searches/:id/stop' => 'twitter_searches#stop'
  post '/users/:user_id/twitter_graphs/:id/stop' => 'twitter_graphs#stop'
  post '/users/:user_id/facebook_searches/:id/stop' => 'facebook_searches#stop'
  
  get '/users/:user_id/twitter_streams/:id/tweets/poll' => 'twitter_streams#poll_tweets', :as => :poll_stream_tweets
  get '/users/:user_id/twitter_streams/:id/poll' => 'twitter_streams#poll_status', :as => :poll_stream_status
  
  get '/users/:user_id/twitter_searches/:id/tweets/poll' => 'twitter_searches#poll_tweets', :as => :poll_search_tweets
  get '/users/:user_id/twitter_searches/:id/poll' => 'twitter_searches#poll_status', :as => :poll_twitter_search_status
  
  get '/users/:user_id/twitter_graphs/:id/poll' => 'twitter_graphs#poll_status', :as => :poll_twitter_graph_status
  
  get '/users/:user_id/facebook_searches/:id/facebook_statuses/poll' => 'facebook_searches#poll_status_count', :as => :poll_facebook_statuses
  get '/users/:user_id/facebook_searches/:id/poll' => 'facebook_searches#poll_status', :as => :poll_fb_search_status
end

app/views/layouts/_copyright.html.erb
<h6>&copy; 2016 <a href="http://www.taalmonsters.nl">De Taalmonsters</a></h6>

app/views/layouts/_menu.html.erb
<ul class="list-unstyled menu">
	<% if @user.admin? %>
	<li class="menu-item <%= "active" if @page_title && @page_title.eql?('twitter_graph') %>"><%= link_to 'Twitter Graph for user', user_twitter_graphs_path(@user.id) %></li>
	<% end %>
	<li class="menu-item <%= "active" if @page_title && @page_title.eql?('twitter_stream') %>"><%= link_to 'Twitter Stream API', user_twitter_streams_path(@user.id) %></li>
	<li class="menu-item <%= "active" if @page_title && @page_title.eql?('twitter_search') %>"><%= link_to 'Twitter Search by Keyword', user_twitter_searches_path(@user.id) %></li>
	<li class="menu-item <%= "active" if @page_title && @page_title.eql?('twitter_id_search') %>"><%= link_to 'Twitter Search by ID', user_twitter_id_searches_path(@user.id) %></li>
	<li class="menu-item <%= "active" if @page_title && @page_title.eql?('facebook_search') %>"><%= link_to 'Facebook Search by Keyword', user_facebook_searches_path(@user.id) %></li>
</ul>
<br>
<br>
<% if current_user.has_data? %>
<%= link_to 'Download all data', user_path(:id => current_user.id, :format => :csv), :class => 'btn btn-info' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
	<li><a>Signed in as <b><%= current_user.name %></b></a></li>
	<li><%= link_to 'Edit profile', edit_user_path(:id => current_user.id) %></li>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand navbar-img" href="http://www.taalmonsters.nl" target="_blank"><img src="http://www.taalmonsters.nl/assets/monsterlogo-136ffd7cdbba5c7e09310c69bca990de.png" class="mini-logo" /></a>
      <%= link_to "SMA Tool", root_path, :class => "navbar-brand" %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>De Taalmonsters - <%= content_for?(:title) ? yield(:title) : "SMA Tool" %></title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SMA Tool" %>">
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<%= render 'layouts/navigation' %>
		</header>
		<main role="main">
			<div class="container-fluid">

				<div id="left-xs" class="col-xs-12 visible-xs">
					<% if @user && !@page_title.blank? %>
					<%= render 'layouts/menu' %>
					<% end %>
				</div>
				<div id="left" class="col-sm-2 visible-sm visible-md visible-lg">
					<% if @user && !@page_title.blank? %>
					<%= render 'layouts/menu' %>
					<% end %>
					<div id="footer">
						<%= render 'layouts/copyright' %>
					</div>
				</div>
				<div id="right-xs" class="col-xs-12 visible-xs">
					<%= render 'layouts/messages' %>
					<% if @page_title %>
					<h1 class="page-header"><%= @sub_title ? @sub_title.titleize : @page_title.titleize %></h1>
					<% end %>
					<% if @user || !@page_title %>
					<%= yield %>
					<% else %>
					<p>
						Please <a href="/sign_in">sign in</a>.
					</p>
					<% end %>
					<div id="footer" class="visible-xs">
						<%= render 'layouts/copyright' %>
					</div>
				</div>
				<div id="right" class="col-sm-10 visible-sm visible-md visible-lg">
					<%= render 'layouts/messages' %>
					<% if @page_title %>
					<h1 class="page-header"><%= @sub_title ? @sub_title.titleize : @page_title.titleize %></h1>
					<% end %>
					<% if @user || !@page_title %>
					<%= yield %>
					<% else %>
					<p>
						Please <%= link_to 'sign in', signin_path %>.
					</p>
					<% end %>
				</div>
			</div>
		</main>
	</body>
</html>